const aboutText = {
    pt: {
        paragraph: 'O conversor de moedas é um projeto feito utilizando React. Para iniciar o projeto local, basta iniciar como uma aplicação React normalmente. \n\n\n Ao selecionar alguma moeda nos selects, são mostradas as bandeiras de todos os países que a utilizam. Clicando em alguma bandeira, é aberta uma nova aba no navegador, redirecionando o usuário a uma pesquisa do Google sobre o país. \n\n\n Os valores monetários são obtidos através [desta API](https://github.com/fawazahmed0/currency-api) onde os valores são atualizados diariamente. Para tradução. foi utilizada a biblioteca react-i18next, e as bandeiras são obtidas com a bibioteca react-world-flags. \n\n\n Possui alguma dúvida, sugestão, ou gostaria entrar em contato comigo? Achou algum erro? Fique à vontade para conversar comigo via [LinkedIn](https://www.linkedin.com/in/rodrigo-de-abreu-costa-a97572b5). Você pode acessar o código fonte do projeto no meu [GitHub](https://github.com/94rodrigo).'
    },
    en: {
        paragraph: 'The currency converter is a project built using React. To start the local project, simply initiate it as a React application normally.\n\n\n When selecting a currency from the dropdowns, flags of all countries using that currency are displayed. Clicking on a flag opens a new browser tab, redirecting the user to a Google search about the country.\n\n\n Monetary values are obtained through [this API](https://github.com/fawazahmed0/currency-api) where values are updated daily. For translation, the react-i18next library was used, and flags are obtained with the react-world-flags library.\n\n\n If you have any questions, suggestions, or would like to get in touch with me, or if you find any errors, feel free to reach out to me via [LinkedIn](https://www.linkedin.com/in/rodrigo-de-abreu-costa-a97572b5). You can access the project\'s source code on my [GitHub](https://github.com/94rodrigo).'
    },
    de: {
        paragraph: 'Der Währungsumrechner ist ein Projekt, das mit React erstellt wurde. Um das lokale Projekt zu starten, starten Sie es einfach wie eine normale React-Anwendung.\n\n\n Wenn Sie eine Währung in den Dropdown-Menüs auswählen, werden die Flaggen aller Länder angezeigt, die diese Währung verwenden. Durch Klicken auf eine Flagge wird ein neuer Browser-Tab geöffnet und der Benutzer zu einer Google-Suche über das Land weitergeleitet.\n\n\n Die Geldwerte werden über [diese API](https://github.com/fawazahmed0/currency-api) bezogen, bei der die Werte täglich aktualisiert werden. Für die Übersetzung wurde die Bibliothek react-i18next verwendet, und die Flaggen werden mit der Bibliothek react-world-flags bezogen.\n\n\n Wenn Sie Fragen, Anregungen haben oder mit mir in Kontakt treten möchten oder wenn Sie Fehler finden, können Sie mich gerne über [LinkedIn](https://www.linkedin.com/in/rodrigo-de-abreu-costa-a97572b5) kontaktieren. Sie können auf meinen [GitHub](https://github.com/94rodrigo) zugreifen, um den Quellcode des Projekts einzusehen.'
    },
    fr: {
        paragraph: 'Le convertisseur de devises est un projet réalisé avec React. Pour démarrer le projet localement, il suffit de le lancer comme une application React normale.\n\n\n Lorsque vous sélectionnez une devise dans les menus déroulants, les drapeaux de tous les pays utilisant cette devise sont affichés. En cliquant sur un drapeau, une nouvelle fenêtre de navigateur s\'ouvre, redirigeant l\'utilisateur vers une recherche Google sur le pays.\n\n\n Les valeurs monétaires sont obtenues via [cette API](https://github.com/fawazahmed0/currency-api) où les valeurs sont mises à jour quotidiennement. Pour la traduction, la bibliothèque react-i18next a été utilisée, et les drapeaux sont obtenus avec la bibliothèque react-world-flags.\n\n\n Si vous avez des questions, des suggestions, ou si vous souhaitez me contacter, ou si vous trouvez des erreurs, n\'hésitez pas à me joindre via [LinkedIn](https://www.linkedin.com/in/rodrigo-de-abreu-costa-a97572b5). Vous pouvez accéder au code source du projet sur mon [GitHub](https://github.com/94rodrigo).'
    },
    es: {
        paragraph: 'El conversor de moneda es un proyecto desarrollado con React. Para iniciar el proyecto localmente, simplemente inícielo como una aplicación React normal.\n\n\n Al seleccionar una moneda en los menús desplegables, se muestran las banderas de todos los países que la utilizan. Al hacer clic en una bandera, se abre una nueva pestaña del navegador, redirigiendo al usuario a una búsqueda en Google sobre el país.\n\n\n Los valores monetarios se obtienen a través de [esta API](https://github.com/fawazahmed0/currency-api), donde los valores se actualizan diariamente. Para la traducción, se utilizó la biblioteca react-i18next, y las banderas se obtienen con la biblioteca react-world-flags.\n\n\n Si tiene alguna pregunta, sugerencia o desea ponerse en contacto conmigo, o si encuentra algún error, no dude en comunicarse conmigo a través de [LinkedIn](https://www.linkedin.com/in/rodrigo-de-abreu-costa-a97572b5). Puede acceder al código fuente del proyecto en mi [GitHub](https://github.com/94rodrigo).'
    },
}

export default aboutText;